### PR TITLE
change for new connector

### PR DESCRIPTION
**Pull request by mossbeard**
The jobresults handed directly.

### CODE REVIEW

**Comment by mossbeard** [comment]
@konne 
No longer necessary, because by downloading the files the old functionality is needed.

**Comment by konne** [comment]
@mossbeard NOP -> like discussed today in the morning

**Comment by konne** [comment]
@mossbeard please send me a request if you I had to review this PR

**Comment by mossbeard** [comment]
@konne 
I have a new request for a review.

**Pull request merged**
